### ISSUE TITLE
Add Prettier and Prettier ESLint

### ISSUE THREAD

**Issue by Alonski** [daostack/arc#205]
### User Story

User story 1: As a developer, I don't want to have to worry about formatting styles. I want code to autoformat whenever I save. I want to completely remove any thinking of formatting from my workflow.

User story 2: As a reviewer, I want to ensure that code is formatted correctly and I don't have to review formatting errors and comment on them.

*Type*: Developer Tool

### Summary: Integrate Prettier and Prettier ESLint into the project. 
There are multiple editor integrations such as VSCode, Sublime, Atom, Vim and more.
In addition with Prettier ESLint we can get the power of ESLint --fix to automatically fix Prettier errors automatically even when not using any plugins.

*Links:*
https://github.com/prettier/prettier/
https://prettier.io/
https://prettier.io/docs/en/eslint.html

### Expected behavior

While coding I have a formatting style guide that I am forced to follow and if I don't I get linting errors which could potentially break builds.

Actual behavior

Currently developers have to think about maintaining the current style of formatting and coding and thinking hard about this wastes time to think of other more important problems.

### Solution

*Summary:*

I will add Prettier and Prettier ESLint integration and write up a Formatting.md file to explain how to use this in a few editors of choice.

### Additional Information

This is open to suggestions/feedback.

**Comment by dkent600** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add collaborators to Dao dashboard page](https://trello.com/c/PzSUWpSY/41-add-collaborators-to-dao-dashboard-page)

**Comment by Alonski** [comment]
Hey @dkent600 what do you mean?

**Comment by dkent600** [comment]
@Alonski I have no idea why trello added that message here.

**Comment by Alonski** [comment]
Haha ok.

**Comment by orenyodfat** [comment]
It more relevant to arc.js
