### ISSUE TITLE
Gather input files from arbitrary depth.

### ISSUE THREAD

**Issue by dev-matan-tsuberi** [daostack/arc#248]
currently `docs/scripts/gen.js` only looks for `.sol` files by using `shell.ls('contracts/*/*.sol')` which will not work for a deeper directory structure.

**Comment by leviadam** [comment]
Why do we have to recompile the files using solc? Can't we use truffle json files?

**Comment by dev-matan-tsuberi** [comment]
@leviadam 
No, I actually checked this beforehand, truffle does not produce `devdoc`,`userdoc`,`gasEstimates`.
https://github.com/trufflesuite/truffle-compile/blob/develop/index.js#L72
http://solidity.readthedocs.io/en/develop/using-the-compiler.html
