### ISSUE TITLE
Revise old documentation.

### ISSUE THREAD

**Issue by orenyodfat** [daostack/arc#272]
all outdated docs are in `docs_old` until revised and either deleted or updated and moved to docs.

in particular revise:
- `roadmap.md`
- `DAO-protocol.md`

**Comment by dev-matan-tsuberi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Arc documentation](https://trello.com/c/k5PtQVq8/1-arc-documentation)

**Comment by dev-matan-tsuberi** [comment]
Solved, all of them are deleted.
