### ISSUE TITLE
`"before all" hook: prepare suite` truffle issue on travis

### ISSUE THREAD

**Issue by dev-matan-tsuberi** [daostack/arc#275]
truffle on Travis still acts funny and fails randomly.

Example:
https://travis-ci.org/daostack/daostack/builds/331780221
![image](https://user-images.githubusercontent.com/33967618/35226843-2a323716-ff95-11e7-86dc-85cdd9a4ffd0.png)

**Comment by dev-matan-tsuberi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Solve “before all hook…” travis error](https://trello.com/c/o0fw8MBd/8-solve-before-all-hook-travis-error)

**Comment by orenyodfat** [comment]
this issue is not being seen any more

**Comment by paulhauner** [comment]
> ![](https://camo.githubusercontent.com/193766a3b9959c5f4ed5cd8cf3251d015e839d51/68747470733a2f2f6769746875622e7472656c6c6f2e73657276696365732f696d616765732f6d696e692d7472656c6c6f2d69636f6e2e706e67) [Solve “before all hook…” travis error](https://trello.com/c/o0fw8MBd/8-solve-before-all-hook-travis-error)

Card not found.

This card may be on a private board. If someone gave you this link, they may need to invite you to one of their boards or teams.
