### ISSUE TITLE
Use withdrawal pattern on all schemes

### ISSUE THREAD

**Issue by orenyodfat** [daostack/arc#281]
Although the most intuitive method of sending/minting Ether,tokens or reputation as a result of an effect, is a direct call, this is not recommended as it introduces a potential security risk. 
The recommendation is to shift to withdrawal pattern.
e.g at the ContributionReward scheme.

**Comment by dev-matan-tsuberi** [comment]
where do we see the withdrawal pattern in `ContributionReward`

**Comment by orenyodfat** [comment]
> where do we see the withdrawal pattern in ContributionReward

instead of sending automatically the reward to a beneficiary upon a positive decision the contract can provide a withdrawal api the beneficiary can use to withdrawal its reward.

**Comment by dev-matan-tsuberi** [comment]
Oh OK, thought you were giving `ContributionReward` as an example of a contract which does use the withdrawal pattern.

**Comment by orenyodfat** [comment]
Done in ContributionReward!
