### ISSUE TITLE
public functions not used internally should be declared external

### ISSUE THREAD

**Issue by dkent600** [daostack/Arc#289]
According to the answer on this page:  https://ethereum.stackexchange.com/questions/19380/external-vs-public-best-practices, `public` functions not used internally should be declared `external` because as such they _may_ cost significantly less gas when invoked, at least when one of the function parameters is an array.

Should we consider changing _all_ unnecessary `public` declarations to `external`?

**Comment by dev-matan-tsuberi** [comment]
Check if we can enforce it in solium

**Comment by orenyodfat** [comment]
The gas diff between external and public is meaningful when passing array as params.
In such cases it worth considering using external.

Please note that most of our contracts can be potentially be inherit by others so..external might not work for them..
