### ISSUE TITLE
VestingScheme permissions of 0x0000000F?

### ISSUE THREAD

**Issue by dkent600** [daostack/Arc#295]
Is there a reason why the VestingScheme test code is setting the VestingScheme permissions to 0x0000000F when it adds the scheme to the dao?  Would 0x00000000 be sufficient?

**Comment by dkent600** [comment]
Another question, why is the VestingScheme test code doing this:

`
   //give some tokens to organization avatar so it could register the universal scheme.
   await testSetup.standardTokenMock.transfer(testSetup.org.avatar.address,30,{from:accounts[1]});
`

Is that necessary?

**Comment by orenyodfat** [comment]
> Is there a reason why the VestingScheme test code is setting the VestingScheme permissions to 0x0000000F when it adds the scheme to the dao? Would 0x00000000 be sufficient?

Yes, 0x00000000 will be sufficient

> //give some tokens to organization avatar so it could register the universal scheme. await testSetup.standardTokenMock.transfer(testSetup.org.avatar.address,30,{from:accounts[1]});

This is remainings from the far old days where there was a fee for registration.
