### ISSUE TITLE
msg.sender pays the vested tokens?

### ISSUE THREAD

**Issue by dkent600** [daostack/Arc#296]
I must be missing something here.  In `VestingScheme.collect`, should this line:

`agreement.token.transfer(agreement.beneficiary, tokensToTransfer);`

(which has the msg.sender paying the tokens)

Actually be:

`agreement.token.transferFrom(this, agreement.beneficiary, tokensToTransfer);`

(which has the vestingscheme paying the tokens)

**Comment by orenyodfat** [comment]
yes,  in agreement.token.transfer(agreement.beneficiary, tokensToTransfer);  the msg.sender paying the tokens... though the msg.sender is the vestingScheme .

**Comment by dkent600** [comment]
OK, I imagined that msg.sender persisted across all of the calls inside the top-level one.  Thanks for the correction.  This can be closed.
