### ISSUE TITLE
"This function is deleted called by the organization."

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#299]
In `VoteInOrganizationScheme`, above `action` there is the comment:

> This function is deleted called by the organization.

Could be replaced with something like:  "`action` is invoked via `controller.genericAction` when the proposal is approved.  It sends the DAO's final vote to the proposal's voting machine".

**Comment by dkent600** [comment]
Second question on docs:

Can we add a comment explaining why the numChoices is incremented by 1?  Here:

```
bytes32 proposalId = intVote.propose(numOfChoices+1, params.voteParams, _avatar, ExecutableInterface(this));
```

**Comment by orenyodfat** [comment]
Re the first q :
It is a spelling issue : delet  call >> delegate call .

I will fix that and will comment on the second .
