### ISSUE TITLE
VoteInOrganizationScheme.action should fire an event?

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#302]
I'm wondering if `VoteInOrganizationScheme.action` should fire an event?  Otherwise how do we know that the vote was ever cast?  I'm not confident thet `NewVoteProposal` is enough, given the loose coupling between the two...

**Comment by orenyodfat** [comment]
There should be event from the voting machine the action function is voting in.
(originalIntVote)

**Comment by dkent600** [comment]
Thing is, just because the vote happened in *our* DAO, doesn't mean that we've forwarded that vote to the "original" DAO.

**Comment by orenyodfat** [comment]
if action is called it means that there is a vote in other organization("original") and in this case you should get a "VoteProposal" event from the "original" voting machine.

**Comment by dkent600** [comment]
VoteProposal is not fired from `action` it is fired from `execute`.

As I mentioned in the original comment, the distant coupling of VoteProposal (in execute) and the execution of `action` makes me nervous.  But maybe that distance is not so great....

**Comment by orenyodfat** [comment]
> VoteProposal is not fired from action it is fired from execute.

VoteProposal is fired on voting from the votingMachine .
https://github.com/daostack/arc/blob/master/contracts/VotingMachines/AbsoluteVote.sol#L278

**Comment by dkent600** [comment]
Sorry, I'm doing too many things at once at the moment.

The events:

1) VoteProposal from the voting machine (represents the vote on this DAO's proposal)

2) ProposalExecuted from VoteInOrganizationScheme.execute which also invokes `action` through a relatively indirect mechanism

The important part never happens until VoteInOrganizationScheme.action

**Comment by orenyodfat** [comment]
> Otherwise how do we know that the vote was ever cast

you should watch for VoteProposal on the voting machine which is being called by action.

**Comment by orenyodfat** [comment]
we can add an event on action..though I am not sure it is a must.

**Comment by orenyodfat** [comment]
adding an event is not a must
