### ISSUE TITLE
VoteInOrganizationScheme Parameters structure is inconsistent

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#303]
I am not sure how much this matters, but the Parameters structure for `VoteInOrganizationScheme` is different from all others like it in Arc.  The order of properties is reversed.

Where this can matter is in the order of items in the array returned by `Scheme.parameters()`.

`VoteInOrganizationScheme`:

```
    struct Parameters {
        IntVoteInterface intVote;
        bytes32 voteParams;
    }
```

All others that just have these two params:

```
    struct Parameters {
        bytes32 voteParams;
        IntVoteInterface intVote;
    }
```

**Comment by orenyodfat** [comment]
each scheme any how has its own param.

**Comment by dkent600** [comment]
of course, this is a question of consistency in how they are defined, but I realize it may not be a big deal.
