### ISSUE TITLE
Add a third array `globalConstraintPreAndPost` in Controller for storage efficiency.

### ISSUE THREAD

**Issue by dev-matan-tsuberi** [daostack/arc#316]
In `Controller` & `UController`. 
we keep two arrays: `globalConstraintPre`, `globalConstraintPost` for each type of constraint (`Pre` & `Post`).
`PreAndPost` constraints are registered twice in both arrays ([here](https://github.com/daostack/arc/blob/globalconstraints-optimization/contracts/controller/Controller.sol#L252) and [here](https://github.com/daostack/arc/blob/globalconstraints-optimization/contracts/controller/Controller.sol#L260)).

We can add a third array `globalConstraintPostAndPre` which will hold only `PreAndPost` constraints.
Now, when we register a `PreAndPost` constraint we register it only once, and the running-time stays the same.

**Comment by orenyodfat** [comment]
decided not to implement that due to overhead and complexity
