### ISSUE TITLE
replace "constant" with "view" or "pure"?

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#320]
According to this:  https://ethereum.stackexchange.com/questions/25200/solidity-what-is-the-difference-between-view-and-constant

Should we replace all uses of "constant" with either "view" or "pure" on functions?

**Comment by orenyodfat** [comment]
The solc compiler should and actually warn about this issue.
If you found a specific place where it need to be changed please add  pointer to.

**Comment by dkent600** [comment]
@orenyodfat  I recommend going through every case of "constant" and replacing it with "pure" or "view".  "constant" appears to be effectively deprecated.

**Comment by orenyodfat** [comment]
please point to one place for example.

**Comment by dkent600** [comment]
Just search for " constant " in *.sol
