### ISSUE TITLE
view/pure/constant function names lack 'get' prefix in GenesisProtocol

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#321]
Often we prefix 'get' to view/pure/constant functions (`getParametersHash`, `getNumberOfChoices`).

But there are a bunch of functions in GenesisProtocol that don't confirm to this pattern.

One example: `redeemVoterReputation`, but there are many.  Apart from consistency in naming, the name of this function, and others like it, imply an action other than "get", like "to redeem something".

I wonder if we need to look at the entire set of contracts to confirm consistency across Arc?

**Comment by orenyodfat** [comment]
@dkent600 Please be more clear about your suggestion or question.

**Comment by dkent600** [comment]
@orenyodfat I notice in the recent PR that you added "get" to a many of the functions, but there are still a bunch of them that lack it.

shouldBoost
score
threshold
voteInfo
votesStatus
isVotable
proposalStatus
totalReputationSupply
proposalAvatar
scoreThresholdParams
staker
voteStake
winningVote
state

**Comment by tibetsprague** [comment]
personally I think that boolean getters like shouldBoost or isVotable are nicer without the get. the rest I agree should have gets

**Comment by orenyodfat** [comment]
Ok. lets leave the boolean getters as is like @tibetsprague suggest..and try to update the rest .
