### ISSUE TITLE
GenesisProtocol functions not covered by tests

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#326]
There appear to be more than one functions of GenesisProtocol that are not being covered by test code.

I haven't counted all of them, but `proposalAvatar` and `scoreThresholdParams` are two examples.

**Comment by orenyodfat** [comment]
These two are covered by https://github.com/daostack/arc/blob/master/test/genesisprotocol.js#L880 
via https://github.com/daostack/arc/blob/master/contracts/test/GenesisProtocolFormulasMock.sol#L17
and https://github.com/daostack/arc/blob/master/contracts/test/GenesisProtocolFormulasMock.sol#L52

Though there might be a room for more explicit test
