### ISSUE TITLE
simple types being returned as struct?

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#327]
In GenesisProtocol, there are a number of instances where simple types appear to be being returned as a struct.

Forgive me if I'm revealing my inexperience with Solidity and wasting anyone's time, but I would like to  help ensure that the code is as simple and clear as possible.

Here is one example, among others:

```
    function proposalAvatar(bytes32 _proposalId) public constant returns(address) {
        return (proposals[_proposalId].avatar);
    }
```

**Comment by orenyodfat** [comment]
avatar type is address.

**Comment by dkent600** [comment]
@orenyodfat Do you see the parentheses around it?  Why are they there?  Note the same thing is happening in other cases that do not return an address.
