### ISSUE TITLE
GenesisProtocol.votesStatus returns too many stati

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#328]
Even though the number of choices is set to 2 and the max number of choices is 10, `GenesisProtocol.votesStatus` returns an array of 11 stati.

**Comment by orenyodfat** [comment]
When max NumberOfChoices is there are actually 11 choices.
include 0- for abstain.

by the way , same for AbsoluteVote 
https://github.com/daostack/arc/blob/master/contracts/VotingMachines/AbsoluteVote.sol#L213

**Comment by dkent600** [comment]
@orenyodfat Why would the function return 11 choices then the proposal only allows 2?  It makes no sense, neither logically nor when looking at the code.  What does `proposal.numOfChoices` mean if not what I have told it:  2?

```
        for (uint cnt = 0; cnt < proposal.numOfChoices; cnt++) {
            votes[cnt] = proposal.votes[cnt];
        }
```

**Comment by orenyodfat** [comment]
see pr #332 .
which changed votesStatus to voteStatus.
