### ISSUE TITLE
redeem... functions can be more clear and consistent

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#329]
I would like to propose that the following functions in `GenesisProtocol` be named more consistently and clearly:

`redeemProposerReputation`
`redeemAmount`
`redeemStakerRepAmount`,
`redeemVoterAmount`
`redeemVoterReputation`

as:

`redeemableReputationProposer`
`redeemableTokensStaker`
`redeemableReputationStaker`
`redeemableTokensVoter`
`redeemableReputationVoter`

or better yet:

`getRedeemableReputationProposer`
`getRedeemableTokensStaker`
`getRedeemableReputationStaker`
`getRedeemableTokensVoter`
`getRedeemableReputationVoter`

**Comment by orenyodfat** [comment]
ok
