### ISSUE TITLE
error in GenesisProtocol doc on vote value

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#334]
In GenesisProtocol.sol, in two places where it says "a value between 0 to and the proposal number of choices"
I believe it should be: "a value >= 0 and < the proposal number of choices".
Needs to be clear it can't be == the proposal number of choices

**Comment by orenyodfat** [comment]
Genesis Protocol is currently a YES/NO voting machine.
You can vote only 1 (NO) or 2 (YES).
There is no abstain(0). 
So actually it can be equal to number of choices.
pr #332 update the funcs comments.
