### ISSUE TITLE
ContributionReward.redeem uses * and .mul

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#340]
Should `ContributionReward.redeem` be using `*` in one case and `.mul` in others?  If so, can we document why?  Thanks!

```
            int reputation = int(periodsToPay) * _proposal.reputationChange;
```
```
            amount = periodsToPay.mul(_proposal.nativeTokenReward);
```

**Comment by orenyodfat** [comment]
mul is from safe math for uint only where reputation is int.
we can add a line in the code comment on that,
