### ISSUE TITLE
In ContributionReward.proposeContribution, _reputationChange not included in _rewards

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#341]
In the params to  `ContributionReward.proposeContribution` would it by any chance be less expensive and cleaner to declare `uint[5] _rewards` as `int[6] _rewards` and include _reputationChange in the array, rather than having it as a separate parameter?

Then where needed we would do:

```
require(_rewards[n] >= 0); 
```

**Comment by orenyodfat** [comment]
require(_rewards[n]` >= 0);  have a cost .
