### ISSUE TITLE
set a fixed version of solidity without the caret e.g 0.4.19.

### ISSUE THREAD

**Issue by orenyodfat** [daostack/arc#343]
Specifying a pragma version with the caret symbol (^) up front tells the compiler to use any version of solidity bigger than the version mentioned  .
This is not a good practice since there could be major changes between versions that would make the code unstable.

**Comment by leviadam** [comment]
There is a question here. What if I want to use the package, but write my own contract with a more advanced version. Will the new compiler be able to compile the old contracts as well?

**Comment by dev-matan-tsuberi** [comment]
@leviadam You can link your contracts against the compiled `.json`. I don't know if it's a good convention/approach though.

**Comment by leviadam** [comment]
OK. We decided not to do it at the moment, due to the reason I stated above.
We leave this issue open as a place holder.
