### ISSUE TITLE
GenesisProtocol doesn't function as a scheme voting machine unless registered in the DAO

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#351]
`GenesisProtocol` doesn't function as a scheme voting machine unless it is also registered in the DAO

More specifically, when a scheme is using `GenesisProtocol` as its voting machine, and you cast a vote "YES", the YES vote is never recorded.  Tibet observed that the proposal is executed with a result of "NO".

This problem disappears when one registers `GenesisProtocol` with the DAO.

**Comment by dkent600** [comment]
Could the problem with `GenesisProtocol` be due to the use of `getParametersFromController`?

Thus with the work-around, the individual scheme's `GenesisProtocol` voting machine is able to use the parameters of the DAO-level GenesisProtocol?

**Comment by orenyodfat** [comment]
Yes. genesisProtocol is also a universal scheme and it need to be registered to the DAO.

**Comment by dkent600** [comment]
@orenyodfat 

1) Then when used, will GP pull the parameters supplied to the DAO-registered GP scheme, or the voting parameters supplied to the scheme that has GP as a voting machine?  If the former, would that be considered an error?

2) In what circumstances would one use the  DAO-registered GP scheme and not the GP as a scheme voting machine?

**Comment by dkent600** [comment]
This needs to be documented, in any case

**Comment by orenyodfat** [comment]
@dkent600 GP is both universal scheme and voting machine.
One always needs to register that to the DAO as a scheme in order to use it as a voting machine.

**Comment by dkent600** [comment]
@orenyodfat Can you please see the questions I posed here:  https://github.com/daostack/arc/issues/351#issuecomment-365601899

Thanks

**Comment by dev-matan-tsuberi** [comment]
@orenyodfat So shouldn't it throw an error when used in an improper way (registered only as a VotingMachines but not as a Scheme)?

**Comment by orenyodfat** [comment]
@dev-matan-tsuberi it might be a good idea to check if is registered as a scheme on the proposal func.

**Comment by dev-matan-tsuberi** [comment]
@orenyodfat It may a good idea to have a `onRegistered(...) returns(bool)` callback function on the voting machine (probably schemes as well) that the controller calls when registering it and reverts if it's getting false.

**Comment by orenyodfat** [comment]
see #469
