### ISSUE TITLE
Need more getters on GenesisProtocol

### ISSUE THREAD

**Issue by tibetsprague** [daostack/arc#354]
I need to be able to get the submittedTime and the proposer and really all of the values in the Proposal struct. Can we add a getter that returns the whole struct (besides the mappings)? That seems better than calling a whole bunch of getters to get each value.

**Comment by orenyodfat** [comment]
proposals is public .
You already have a getter for a proposal.
see here for reference : https://github.com/daostack/arc/blob/master/test/genesisprotocol.js#L120
This issue should move to arc.js

**Comment by dkent600** [comment]
`proposals` can be used without an arc.js wrapper.  But it could be handy to document and enforce the structure (for typescript) of a proposal by defining the interface in the d.ts.

**Comment by tibetsprague** [comment]
ah somehow missed that, thanks guys
