### ISSUE TITLE
revert on GenesisProtocol.vote

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#360]
I'm getting a revert on `GenesisProtocol.vote` that I can't immediately explain, and in the interest of time I'm reporting it a little sooner that I might normally:

We have created a DAO with the GenesisScheme and these founders:
```
      {
        address: accounts[0],
        reputation: web3.toWei(1000),
        tokens: web3.toWei(100)
      },
      {
        address: accounts[1],
        reputation: web3.toWei(1000),
        tokens: web3.toWei(100)
      }
```

We're going to add then remove a GC, first propose to add:

``` 
    const tokenCapGC = await dao.getScheme("TokenCapGC");

    const globalConstraintParametersHash = (await tokenCapGC.setParams({
      token: dao.token.address,
      cap: 3141
    })).result;

    const globalConstraintRegistrar = await helpers.getDaoScheme(dao, "GlobalConstraintRegistrar", GlobalConstraintRegistrar);

    const votingMachineHash = await helpers.getSchemeVotingMachineParametersHash(dao, globalConstraintRegistrar);
    const votingMachine = await helpers.getSchemeVotingMachine(dao, globalConstraintRegistrar);

    let result = await globalConstraintRegistrar.proposeToAddModifyGlobalConstraint({
      avatar: dao.avatar.address,
      globalConstraint: tokenCapGC.address,
      globalConstraintParametersHash: globalConstraintParametersHash,
      votingMachineHash: votingMachineHash
    });
```

Vote on the proposal to add:

```
    let proposalId = result.proposalId;
    await helpers.vote(votingMachine, proposalId, 1, web3.eth.accounts[0]);
```

Now propose to remove the GC:

```
    result = await globalConstraintRegistrar.proposeToRemoveGlobalConstraint({
      avatar: dao.avatar.address,
      globalConstraint: tokenCapGC.address
    });
```

And vote on it, using the same voting machine that we used to vote on adding the GC, but a different voter.  This vote is where the revert occurs:

```
    proposalId = result.proposalId;
    await helpers.vote(votingMachine, proposalId, 1, web3.eth.accounts[1]);
```

` helpers.vote` does the following and works fine everywhere else:

```
  await votingMachine.vote(proposalId, vote, { from: (voter ? voter : accounts[0]) });
```

**Comment by orenyodfat** [comment]
@dkent600 please send a link to your test code

**Comment by dkent600** [comment]
@orenyodfat https://github.com/daostack/arc.js/tree/93f4fc3c7bbd26648bcaeb00cb47a8fa3a82ed4c

**Comment by orenyodfat** [comment]
@dkent600 does the same test with tokenCapGC pass with absoluteVote ?
I just fixed an issue with tokenCapGC #362 which might be related.
I also added a test to add and remove gc with genesis protocol. 
https://github.com/daostack/arc/blob/tokencap/test/globalconstraintregistrar.js#L209

**Comment by dkent600** [comment]
@orenyodfat 

> does the same test with tokenCapGC pass with absoluteVote 

It works with AbsoluteVote, but honestly, there continue to be issues with the Arc.js test code relating to rigorously using the schemes' voting machine rather than the universal one.  One of the problems with AbsoluteVote that I hit today has been that ownerVote never seems to cause execution when it should, and afterwards a vote by accounts[0] always results in `CancelVoting` followed by `VoteProposal` but still no execution.  I'm only able to get proposal execution by voting with accounts[1].

The accounts look like this:

```
      {
        address: accounts[0],
        reputation: web3.toWei(1000),
        tokens: web3.toWei(100)
      },
      {
        address: accounts[1],
        reputation: web3.toWei(1000),
        tokens: web3.toWei(100)
      }
```

I'm spending a lot of time refactoring and correcting the Arc.js text code, but am not at the end.  I'm really pushing to determine where the problems lie (Arc or Arc.js).

**Comment by dkent600** [comment]
@orenyodfat OK, I have been under the conception that percVote of 50 meant that 50% of the reputation could finish the vote.  But it seems it has to be > 50%.  Is that the correct behavior?

**Comment by orenyodfat** [comment]
Yes. it should be more than 50%.
the doc should be updated.
is that the issue you found ?

**Comment by dkent600** [comment]
@orenyodfat I think that is  basically it for now.  We can probably close this.

**Comment by dkent600** [comment]
@dev-matan-tsuberi  heads up on the need to fix the docs
