### ISSUE TITLE
Add a DAICO scheme

### ISSUE THREAD

**Issue by tibetsprague** [daostack/arc#374]
This form of ICO is growing in popularity and definitely seems like something we should support out of the box. 

https://ethresear.ch/t/explanation-of-daicos/465
https://medium.com/theabyss/the-worlds-first-daico-remodeling-the-token-sale-df3b56a8df9e

**Comment by leviadam** [comment]
The simple ICO scheme for an organization is basically a DAICO, all that is needed is to print also reputation printing. It can be nice.

**Comment by orenyodfat** [comment]
It will be implemented for a case of a real demand
