### ISSUE TITLE
GenesisProtocol.RedeemReputation event should provide avatar

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#375]
To be consistent, should GenesisProtocol.RedeemReputation event provide the _avatar?

Contribution reward does....

Can we make them consistent?

**Comment by orenyodfat** [comment]
ContributionReward and GenesisProtocol are 2 different animals.
Not sure about keep them consistence to each other,

**Comment by dkent600** [comment]
@orenyodfat  Why is avatar useful in one case and not the other?  Are we sure these two are different for good reasons?

It would be helpful for Arc.js, if these events mean different things, to give the events different names.
