### ISSUE TITLE
ContributionReward.organizationsProposals returns undefined for redeemedPeriods

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#378]
`ContributionReward.organizationsProposals` always returns `undefined` for `redeemedPeriods`

I'm calling:

```
const proposal = await ContributionReward.organizationsProposals(avatar, proposalId)
```

This is supposed to give me an array of length 11, but in fact is returning an array of length 10.  `redeemedPeriods` is therefore undefined.  The rest of the items look good.

I need it for this: https://trello.com/c/i5KNMsM2

**Comment by orenyodfat** [comment]
You can use getPeriodsToPay https://github.com/daostack/arc/blob/master/contracts/universalSchemes/ContributionReward.sol#L349 to get the number of periods left to be paid for any reward type.
