### ISSUE TITLE
UniversalScheme.updateParameters can be removed?

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#387]
`UniversalScheme.updateParameters` does not appear to be in use.  

Nor is the `hashedParameters` member variable that is defined in UniversalScheme.

Can these be removed?

Either that, or can they be documented as to why they exist?

**Comment by orenyodfat** [comment]
This is to provide a unified interface for scheme's owner to update or add scheme's param.
Currently we do not have any universal scheme which using that.
We might consider to make UniversalScheme noneOwnable .so updating a scheme should be via a proposal. @leviadam ?
