### ISSUE TITLE
Can scheme.setParameters check for hash existence before storing anything?

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#388]
In the interest of saving gas and reducing the (perceived) number of transactions (esp when creating a new DAO), can we have `scheme.setParameters` check, before storing anything, whether the given hash value has already been recorded?

See https://github.com/daostack/arc.js/issues/9

**Comment by dkent600** [comment]
I have reason to believe that this could reduce the number of transactions to the bare minimum when creating a new DAO.

**Comment by dkent600** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Audit Arc.js for unnecessary transactions](https://trello.com/c/xz57eejh/35-audit-arcjs-for-unnecessary-transactions)

**Comment by orenyodfat** [comment]
How about calculating the param hash (off chain) and just check if it exist at the parameters mapping(on chain) before setting the param?

**Comment by dkent600** [comment]
@orenyodfat I will give that a try

**Comment by dkent600** [comment]
@orenyodfat 

> How about calculating the param hash (off chain) and just check if it exist at the parameters mapping(on chain) before setting the param?

This is proving to be not easy to implement in Arc.js.  There is some pretty ugly code involved.  Further, there is not as much to gain here as I thought there might be.

1) Not easy because computing the hash of a packed set of values involves maintaining the name of the data type for each parameter in every contract and a hack for checking whether a given hash value has not previously been saved ([see here](https://github.com/daostack/arc.js/blob/c7c07df63e897464ebaaf77c4fa22f2704513bcc/lib/utils.ts#L225)).

2) ugly because a [special case is required for TockenCapGC](https://github.com/daostack/arc.js/blob/c7c07df63e897464ebaaf77c4fa22f2704513bcc/lib/utils.ts#L234), and a [really ugly special case for GenesisProtocol](https://github.com/daostack/arc.js/blob/c7c07df63e897464ebaaf77c4fa22f2704513bcc/lib/contracts/genesisProtocol.ts#L900).

3) Not as much to gain as I thought because:

    a) AbsoluteVote parameters include a reputation address which is unique for each DAO, therefore AbsoluteVote parameters will never already exist the first time they are saved for a DAO.  This is not a factor if GenesisProtocol is used as the voting machine.  AbsoluteVote is the Arc.js default, but Alchemy is using GenesisProtocol.

    b) Any scheme with AbsoluteVote as the voting machine will have a problem for the same reason as a) above.

**Comment by dkent600** [comment]
@orenyodfat 

> How about calculating the param hash (off chain) and just check if it exist at the parameters mapping(on chain) before setting the param?

This is proving to be not easy to implement in Arc.js.  There is some pretty ugly code involved.  Further, there is not as much to gain here as I thought there might be.

1) Not easy because computing the hash of a packed set of values involves maintaining the name of the data type for each parameter in every contract and a hack for checking whether a given hash value has not previously been saved ([see here](https://github.com/daostack/arc.js/blob/c7c07df63e897464ebaaf77c4fa22f2704513bcc/lib/utils.ts#L225)).

2) ugly because a [special case is required for TokenCapGC](https://github.com/daostack/arc.js/blob/c7c07df63e897464ebaaf77c4fa22f2704513bcc/lib/utils.ts#L234), and a [really ugly special case for GenesisProtocol](https://github.com/daostack/arc.js/blob/d05693d03ec2c987ffb21f06908b18cb8372dca6/lib/contracts/genesisProtocol.ts#L900), and [another ugly one for VoteInOrganizationScheme](https://github.com/daostack/arc.js/blob/d05693d03ec2c987ffb21f06908b18cb8372dca6/lib/contracts/voteInOrganizationScheme.ts#L73).

3) Not as much to gain as I thought because:

    a) AbsoluteVote parameters include a reputation address which is unique for each DAO, therefore AbsoluteVote parameters will never already exist the first time they are saved for a DAO.  This is not a factor if GenesisProtocol is used as the voting machine.  AbsoluteVote is the Arc.js default, but Alchemy is using GenesisProtocol.

    b) Any scheme with AbsoluteVote as the voting machine will have a problem for the same reason as a) above.

**Comment by orenyodfat** [comment]
I guess it is better to add complexity to arc.js than solidity code.

In addition I would like to avoid adding additional condition in the contract as in some cases (maybe most cases) it will not be require.

**Comment by dkent600** [comment]
Just sayin', everyone, not just Arc.js users, would benefit from adding a boolean 'hasValue' parameter to each struct, in terms of saving on transactions, using it to avoid saving params that are already saved.  That code change would be *much* simpler than what I'm having to do in Arc.js.

**Comment by orenyodfat** [comment]
Disagree

**Comment by dkent600** [comment]
> Disagree

In which respect?  (just want to get the pros and cons here)

**Comment by dkent600** [comment]
Just FYI, I have found a way to reduce the ugliness in the special cases of GenesisProtocol and VoteInOrganizationScheme, though it is still not pretty.

[Here](https://github.com/daostack/arc.js/blob/1c837c57bd19dec8b084d8e172835544a2052908/lib/contracts/genesisProtocol.ts#L899) and [here](https://github.com/daostack/arc.js/blob/1c837c57bd19dec8b084d8e172835544a2052908/lib/contracts/voteInOrganizationScheme.ts#L71).

**Comment by leviadam** [comment]
How about we add a log when a params are added to the dictionary.

**Comment by dkent600** [comment]
@leviadam 

> How about we add a log when params are added to the dictionary?

I don't have numbers, but I strongly suspect that checking logs is a time consuming operation as the logs grow.  I will do a timing test on the case of filtering for a single event.

I'm not sure we would want to cache and watch all the events...I'm uneasy with the memory implications.

**Comment by dkent600** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Replace parameters hashing by a different method to save TXs.](https://trello.com/c/bymki9T5/5-replace-parameters-hashing-by-a-different-method-to-save-txs)

**Comment by dkent600** [comment]
@orenyodfat Why was this closed?

**Comment by orenyodfat** [comment]
It was close because the check of existing param can be done via a pre call from the client for free.

**Comment by dkent600** [comment]
> It closed because the check of existing param can be done via a pre call from the client for free.

That check gives a false negative when all parameter values have been set to zero and persisted as such.
