### ISSUE TITLE
Make sure that proposal IDs are unique across the entire system

### ISSUE THREAD

**Issue by tibetsprague** [daostack/arc#395]
Right now proposal IDs are only unique within a voting machine. This means we need to check proposalID + dao avatar address to make sure of uniqueness. And actually even this might not work if a DAO decides to change voting machines at some point. For app development it would be much easier to know that proposal IDs will just be unique

**Comment by orenyodfat** [comment]
@dev-matan-tsuberi 👍

**Comment by orenyodfat** [comment]
DAOstack voting machines implementation provides uniqueness  across proposalIds.
One can trick that by implementing its own voting machine though this would make the voting machine not trustable anyhow.

**Comment by dkent600** [comment]
> DAOstack voting machines implementation provides uniqueness across proposalIds.

Indeed, a while back when I read the code:

```
bytes32 proposalId = keccak256(this, proposalsCnt);
```

I didn't realize that `this` was being hashed too.

**Comment by dkent600** [comment]
@orenyodfat 

> One can trick that by implementing its own voting machine though this would make the voting machine not trustable anyhow.

Regarding this:  https://github.com/daostack/arc.js/issues/93

Should Arc.js support non-Arc voting machines?
