### ISSUE TITLE
Need to know the amount that will be redeemed

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#396]
In order to approve a transfer of external tokens before they are redeemed by ContributionReward, we need to know how many tokens are going to be redeemed.  What would be ideal in this case would be if all of the redeem functions, instead of returning true or false, would return the amount redeemed.

(Then the javascript can `call` the redeem function and get the return value without actually executing it.)

**Comment by orenyodfat** [comment]
There is no need to approve anything for redeeming

**Comment by dkent600** [comment]
@orenyodfat This test fails if the transfer is not approved:

https://github.com/daostack/arc.js/blob/3763ae8c1274d370c0f0576484fa9fe7c6005c5b/test/contributionreward.js#L144

**Comment by dkent600** [comment]
Thanks @orenyodfat for finding the bug in the arc.js test!

**Comment by dkent600** [comment]
@orenyodfat (although I think this could still be a nice feature to have)
