### ISSUE TITLE
Unrequired token approvals should be removed in test/genesisprotocol.js

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#399]
In test/genesisprotocol.js there are multiple cases where token transfers are being approved where they are not supposed to be required (ie, where .stake() is not being called).  I think these should be removed to confirm that the approval is not, in fact, required, and to provide proper examples of how the code should work.

The approvals look like this:

```
await testSetup.standardTokenMock.approve(testSetup.genesisProtocol.address, N);
```

**Comment by orenyodfat** [comment]
there is only one place..
are you seeing multiple ?

**Comment by dkent600** [comment]
Looking more carefully, you are right:  just the one.
