### ISSUE TITLE
Consider a mechanism by which earning from staking is proportional to how early the staking was made

### ISSUE THREAD

**Issue by dev-matan-tsuberi** [daostack/arc#402]
to avoid risk less profit being made by placing a large stake when the casting vote is detected and not yet mined.

Possible solution: https://docs.google.com/document/d/1EbcI-ZnTBWUYqFwtyoFvy9inXc_GQXdxaMKIr_AjxhU/edit#heading=h.bmqykvgm6vim

**Comment by dev-matan-tsuberi** [comment]
Closed.

**Comment by dkent600** [comment]
I'm curious why this was closed?  Was it considered and rejected for some reason?

**Comment by dev-matan-tsuberi** [comment]
@orenyodfat said he had talked it out with @leviadam and @fmatan and eventually reached the conclusion that it was not an issue. Asked me to close it.
