### ISSUE TITLE
TokenCapGC has inconsistent name "params"

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#406]
The TokenCapGC contract parameters mapping is named "params", whereas all the other contracts have it named "parameters".

This one special case makes it awkward to write code that works for all contracts that have parameters. Can we rename the mapping to "parameters"?

**Comment by dkent600** [comment]
This is part of the effort to minimize transactions [here](https://github.com/daostack/arc/issues/388)

**Comment by orenyodfat** [comment]
How it will minimize transactions ?

**Comment by dkent600** [comment]
@orenyodfat see [here](https://github.com/daostack/arc/issues/388).  

The idea is to stop saving redundant sets of parameters.

I think in any case we should strive for consistency in the contract APIs.

**Comment by orenyodfat** [comment]
Still not sure how it will minimize the number of txs to the blockchain ?
Are you ?

**Comment by dkent600** [comment]
This question is being posed in the wrong ticket.  In any case, yes I'm sure:  Whenever we save parameters to the chain we are incurring a transaction.

**Comment by dkent600** [comment]
Having said that ^^^^, with respect specifically to TokenCapGC, how often will we save transactions by checking for previously-saved params?  I don't know how often that use case will occur, but not a lot.  It certainly does not affect `DAO.new`, which is the prime directive in this context.

What I _do_ know is that it is prefereable in Arc.js to have a consistent API for all Arc contracts and Arc.js contract wrappers, where special cases are minimized and all knowledge about doing this check can be encapsulated inside a common function in Arc.js (better yet, inside of Arc).  This goal is compromised unless we make the requested change.

**Comment by orenyodfat** [comment]
Yes.though how come  vars naming is relevant to save txs ?

**Comment by dkent600** [comment]
> Yes.though how come  vars naming is relevant to save txs

Because we are calling contract.parameters(aHash) in every other case where we try to determine whether a set of parameters has already been saved.

**Comment by orenyodfat** [comment]
So ,you can have a special call for token cap ...and still keep the same tx
number .
The interface does not explicitly define vars names so you can not make any
assumption on that .
It is  issue related namimg which does not have nothing related to save txs

**Comment by dkent600** [comment]
Yes, transactions are the subject of another ticket.  This ticket is about naming and making Arc easier to program against.  We have the same goal with Arc.js -- make it easy to use.  Why not also with Arc, now and going forward?
