### ISSUE TITLE
Missing `preBoostedVotePeriodLimit` in `Proposal` struct in `GenesisProtocol`

### ISSUE THREAD

**Issue by dev-matan-tsuberi** [daostack/arc#413]
the `Proposal` struct includes `boostedVotePeriodLimit`, why doesn't it also include `preBoostedVotePeriodLimit`?

**Comment by orenyodfat** [comment]
boostedVotePeriodLimit is updated per proposal during the proposal life to support quietEnding.
preBoostedVotePeriodLimit is set  be the dao and is general for all proposals.

**Comment by dev-matan-tsuberi** [comment]
@orenyodfat But what happens if I make a proposal and then change `preBoostedVotePeriodLimit`?
Does the new value of `preBoostedVotePeriodLimit` apply to the old proposal?

**Comment by dev-matan-tsuberi** [comment]
`paramsHash` is stored in the proposal struct since fd3b639737008d290f87e9ac9b62e743a7e81ed2 . So we can retrieve `preBoostedVotePeriodLimit` from that.
