### ISSUE TITLE
GenesisProtocol.Proposal.totalStakes comment is correct?

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#418]
In GenesisProtocol, the  comment for `Proposal.totalStakes` says:

"[(total stakes - votersStakes)],[totalRedeemableStakes]"

But looking at the code, it seems to me it should be:

[(total redeemable (total staked minus the fee))],[total staked (including staking fee)]

In other words, it seems wrong to say that [1] is "totalRedeemableStakes"

**Comment by orenyodfat** [comment]
All stakes is redeemable . (stakersstake + votersfee).

**Comment by dkent600** [comment]
I guess it begs the question "redeemable by whom?".  I think the comments given here are more clear:

|  | computation | comment |
| -- | -- | -
| proposal.totalStakes[0] | amount staked minus  fee | Total number of  tokens staked and redeemable by stakers |
| proposal.totalStakes[1] | amount staked | Total number of  tokens staked and redeemable by everyone |

**Comment by orenyodfat** [comment]
proposal.totalStakes[1] - Total number of redeemable tokens..as this value decrease on each redeem .
