### ISSUE TITLE
Ensure we can deploy the minimum acceptable number of founders

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#419]
Suggestion::  Make a business decision about the minimum acceptable number of founders we can live with, from a business perspective, and then add a test to Arc that ensures that we can forge a DAO with at least that number of founders.  The test would need to incorporate an estimated mainnet block gas limit.

Motivation:  Suppose it comes about that it is only possible to forge a DAO with two founders.  That would be a business issue, and somebody is going to need to know about it, and quickly.

**Comment by orenyodfat** [comment]
The limitation on the number of founders is relevant only for DAOCreator , which is an helper to create a DAO.
Actually one can create a DAO with any number of founders by creating it directly (without DAOCreator).
It might be a good idea to document this gas constraint limitation of DAOCreator somewhere.
