### ISSUE TITLE
broken docs links

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#427]
I haven't done a thorough check of links in the documentation pages, but I find that that these two are broken:

https://daostack.github.io/arc/contracts/universalSchemes/
https://daostack.github.io/arc/contracts/globalConstraints/

**Comment by dev-matan-tsuberi** [comment]
should be: 
https://daostack.github.io/arc/contracts/universalSchemes/README
https://daostack.github.io/arc/contracts/globalConstraints/README

Can you point to the location where these links showed up?

**Comment by dkent600** [comment]
Where I found them was here: https://daostack.github.io/arc/README/#the-structure-of-a-dao

But I can't say they aren't elsewhere as well.
