### ISSUE TITLE
Sanity check the parameters passed in to GenesisProtocol

### ISSUE THREAD

**Issue by tibetsprague** [daostack/arc#438]
Right now in Arc.js proposingRepRewardConstB is by default set to web3.toWei(5) which is way way way way too big. It should not be converted to WEI, and probably shouldn't be bigger than 1. We need sane minimums and maximums enforced by Arc. 

Connected to https://github.com/daostack/arc.js/issues/196

**Comment by dkent600** [comment]
See also https://github.com/daostack/arc.js/issues/196#issuecomment-381711923

**Comment by orenyodfat** [comment]
done
