### ISSUE TITLE
add proposals mapping to GlobalConstraintRegistrar 

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#446]
All schemes except `GlobalConstraintRegistrar` have a way to obtain a proposal given the proposalId.

For example, with `ContributionReward`:

```
mapping(address=>mapping(bytes32=>ContributionProposal)) public organizationsProposals;
```

`GlobalConstraintRegistrar` proposals are stored in a mapping that is a property of `Organization`.  The `Organization` struct is accessible via:

```
mapping(address=>Organization) public organizationsData;
```

However the `proposals` and `voteToRemoveParams` mappings properties of `Organization` are not exposed by that mechanism.

**Comment by dkent600** [comment]
This issue is a problem for implementing:  https://github.com/daostack/arc.js/issues/116

**Comment by orenyodfat** [comment]
How about  :  
organizationsData[_avatar].proposals[_proposalId] ?

**Comment by dkent600** [comment]
The proposals mapping is not exposed, not accessible
