### ISSUE TITLE
AbsoluteVote: last voter pays for potentially very expensive execution

### ISSUE THREAD

**Issue by dev-matan-tsuberi** [daostack/arc#457]
In `AbsoluteVote`, the proposal gets executed when a voter passes the threshold (50%) when voting.
Since executing a proposal is potentially very expensive (can run arbitrary code on the blockchain), it may be wrong to require the last vote to also execute the proposal.

**Comment by dwking2000** [comment]
one solution could be to allowing users to sign messages that will execute when a third party relayer picks it up. Relayers can be incentivized by bounties or some other method. Initial relay could be run by DAO Stack or other interested parties. There is talk of standardizing this technique in an ERC proposal, but for now it could be done in a similar way to other projects that are doing this.

**Comment by dev-matan-tsuberi** [comment]
I like the refund option since its not a breaking change, though how would you know in soliditu how much to refund the user?

**Comment by dkent600** [comment]
> how would you know in solidity how much to refund the user?

Via the returned tx:

https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethgettransactionreceipt

**Comment by orenyodfat** [comment]
A possible solution is to let the dao pay for the voting txs and enable offchain voting.
Making the voters happier. 
Already starting to doing some moves towards ...

**Comment by dev-matan-tsuberi** [comment]
@orenyodfat 
how will off-chain voting work (plasma is not yet an option)? what are you cooking up? i'm curious :)

**Comment by orenyodfat** [comment]
This will be solved as part of future off-chain solution in the future
