### ISSUE TITLE
Add ExpireContract to IntVoteInterface

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#458]
Would like to consider adding ExpireContract be added as an event in IntVoteInterface, and be implemented in GP.  I know it is currently possible for the user to detect this by checking the execution state in the GP ExecuteProposal method, but I suspect that expiration could be common among voting machines and would be good for Arc.js to provide this as one of the events in IntVoteInterface, allowing the user to watch it in a voting machine-agnostic way.

**Comment by dkent600** [comment]
See also #455

**Comment by leviadam** [comment]
Hi doug,

Not sure I understand. Can you be more specific?

**Comment by dkent600** [comment]
Sorry, definitely was not clear, especially because it doesn't really make sense, or if it makes sense, I don't know what I was saying either.

Looks like I was asking for a new event called `ExpireContract`  (I think I must've meant `ExpireProposal`) and for this event to somehow be fired when the proposal expires.  However, clearly that is not possible.

So I'm closing this.
