### ISSUE TITLE
ContributionReward#getPeriodsToPay only works for executed proposals

### ISSUE THREAD

**Issue by tibetsprague** [daostack/arc#468]
In Alchemy there are times when we want to know what someone's rewards for a proposal will be before the proposal has been executed, for example after a boosted proposal expires and passes because it has more yes votes than no, so people can redeem the proposal even though it has not been executed yet (we execute it as part of the redeeming). But right now getPeriodsToPay will return 0 if the proposal has not been executed. Can we instead have it just return the total number of periods for the proposal in that case? We could also handle this in arc.js, but seems ideal to handle it at the source.

**Comment by orenyodfat** [comment]
How about reading proposal.numberOfPeriods ?

**Comment by tibetsprague** [comment]
sure we can, but this still may be a change we want to make in arc at some point

**Comment by orenyodfat** [comment]
if there is no execution so getPeriodsToPay should return 0.

**Comment by dkent600** [comment]
@orenyodfat Can we reopen this (see [comment](https://github.com/daostack/arc/issues/468#issuecomment-393713449) above).
