### ISSUE TITLE
AbsoluteVote should be a scheme like GenesisProtocol.

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#469]
AbsoluteVote should be a scheme like GenesisProtocol.  Part of doing this would involve removing the votingMachine params hash from the params of all the schemes that have a voting machine, as they will no longer need the params hash to call `propose` on their voting machine..

Should also apply to `QuorumVote`.

This will make all the voting machines consistent in their behaviour, simplifying coding against Arc.

Both Arc.js and Vanille would benefit from this change.

**Comment by orenyodfat** [comment]
There is some disadvantage having GenesisProtocol as a scheme , as one cannot use it as a stand alon component.
We are considering changing that.

**Comment by orenyodfat** [comment]
done in infra
