### ISSUE TITLE
There is no way to get the parameters of a global constraint

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#470]
There is no way to get the parameters of a given global constraint (not that I have found, anyway).

So I propose that we add a function `Controller.getGlobalConstraintParameters`, similar to the existing `Controller.getSchemeParameters`.

Vanille needs this to enable the user to see the current parameters of given global constraint before modifying them.

**Comment by orenyodfat** [comment]
You can get the length of globalConstraintsPre and globalConstraintsPre using globalConstraintsCount and then iterate over these array.

**Comment by dkent600** [comment]
> You can get the length of globalConstraintsPre and globalConstraintsPre using globalConstraintsCount and then iterate over these arrays.

`Controller.getGlobalConstraintParameters` would be simple to implement and would be consistent with `Controller.getSchemeParameters` in reasoning and API design pattern.

The suggested alternative is neither consistent nor obvious/intuitive, and requires extra coding at the client.

**Comment by dkent600** [comment]
Further problem with the suggestion solution:  I believe the globalConstraintsPre will not be accessible, being buried inside the Organization struct.

**Comment by orenyodfat** [comment]
it is preferable adding complexity to client code than to the contract .
Any how it seems to be low priority .

**Comment by orenyodfat** [comment]
globalConstraintsPre Is a public array which provid automatic getter by
index .
No issue with that

**Comment by dkent600** [comment]
Mappings and arrays aren't exposed when they are members of a struct.  This is the case in UController.
