### ISSUE TITLE
Multiple issues related to proposer being set to 0 on GenesisProtocol.redeem

### ISSUE THREAD

**Issue by tibetsprague** [daostack/arc#501]
It seems strange to set the proposer to 0, because then we lose the information of who the proposer was.

**Comment by tibetsprague** [comment]
Ah, i see now that the idea is that it is used to tell whether the proposer has redeemed their rewards yet. But there is actually another bug where getRedeemableReputationProposer still returns a value even after redeem has been called (and proposer set to 0). So that should be fixed, although i do think there is still value in keeping around the proposer address even after redeeming, regardless. We actually do want it in alchemy

**Comment by orenyodfat** [comment]
We might consider to make getRedeemableReputationProposer internal func  as it can be calculated off chain.

**Comment by tibetsprague** [comment]
still seems a bit odd to make developers who want to track the proposer of a proposal look through events, a more complicated and slow process than just pulling the value from the chain. seems to me that proposer is such a fundamental part of a proposal that we would want that stored on the proposal in perpetuity. though i do also see that we want a way to track whether the proposer has redeemed their reputation or not. seems like we could/should do this similarly to how it is handled for voters and stakers. 

i do agree that getRedeemableReputationProposer could be calculated off chain. are you specifically thinking that arc.js should do it? @dkent600

**Comment by orenyodfat** [comment]
Well , the ideal will be to remove the proposal data once it is executed
and keep only the needed info for redeeming .
The general concept is that the contract does not need to maintain the
history of proposal (or any action) .
This can be done with events(logs).
Re the offchain calculation of the available redemption (any kind ) I think
that arc.js should and can support that.

**Comment by orenyodfat** [comment]
We might even consider to clear out any proposals vars which are not needed
for the proposal redemption on the proposal execution point

**Comment by tibetsprague** [comment]
@orenyodfat reopening because @dkent600 @dev-matan-tsuberi and I all think that we shouldnt reimplement getRedeemableReputationProposer in javascript, the logic should be in place in Arc, and it should return 0 if the proposer already redeemed their rewards
