### ISSUE TITLE
Remove `public` on `balances` in Reputation and remove decimals

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#510]
Remove `public` on `balances` in Reputation.  We have `reputationOf` for that.  Otherwise we are needlessly exposing the contract's internal implementation and will have to support it.  Changing it therefore becomes increasing difficult as time passes and people become dependent on it.

Remove `decimals`, it doesn't appear to be in use.

**Comment by leviadam** [comment]
These things are there in order to keep compatibility with erc20.
