### ISSUE TITLE
GP error in getRedeemableReputationStaker with votersGainRepRatioFromLostRep?

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#516]
In `GenesisProtocol.getRedeemableReputationStaker`, according to the code comments on `votersGainRepRatioFromLostRep`, should this line:

```
rep = (amount * ( proposal.lostReputation - ((proposal.lostReputation * params.votersGainRepRatioFromLostRep)/100)))/proposal.stakes[proposal.winningVote];
```

be:

```
rep = (amount * ( proposal.lostReputation - ((proposal.lostReputation * (100 - params.votersGainRepRatioFromLostRep))/100)))/proposal.stakes[proposal.winningVote];
```

**Comment by orenyodfat** [comment]
Let P = Y percent of X
So 
X-P = (100-Y) percent of X
now:
X = proposal.lostReputation
Y = params.votersGainRepRatioFromLostRep
P = (proposal.lostReputation * params.votersGainRepRatioFromLostRep)/100)
so 
     X                                                                                           P
proposal.lostReputation - ((proposal.lostReputation * params.votersGainRepRatioFromLostRep)/100) = 
((100 - params.votersGainRepRatioFromLostRep)* proposal.lostReputation)/100

so it is the same..
