### ISSUE TITLE
Add `GenesisProtocol.expiredProposals

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#518]
Would be useful to have a function `GenesisProtocol.expiredProposals(address _avatar)`.  This would enable Arc.js to easily calculate the number of boosted proposals that are not expired.

Could look like this:

```solidity
function expiredProposals(bytes32 _paramsHash,address _avatar) public view returns(int) {
  if (proposalsExpiredTimes[_avatar].count() != 0) {
      // solium-disable-next-line security/no-block-members
      return proposalsExpiredTimes[_avatar].rank(now);
   } 
  return 0;
}
```

**Comment by dkent600** [comment]
> Where do you see this func ?

Sorry, that was a really unclear question.

I copied the suggested code from `threshold`, which itself returns `int`.  The question is really:  why does `threshold` return `int` and not `uint`?

**Comment by dkent600** [comment]
> Why are.js needs to calculate that

Arc.js would like to wrap the Genesis property `orgBoostedProposalsCnt`, but that property is not very useful since it includes expired proposals.

**Comment by orenyodfat** [comment]
Not sure you need that .
I might turn orgBoostedProposalcnt to private as well

**Comment by orenyodfat** [comment]
It is int because it is compared to score which is int .
We can turn that to uint and do the casting on the compare ...If this a
really needed

**Comment by orenyodfat** [comment]
I guess it will be usefull and relative cheap to have
getNumberOfBoostedProposals func
I will add that

**Comment by orenyodfat** [comment]
added at #517
