### ISSUE TITLE
Locking4Reputation totalLocked and totalLockedLeft can be more clear

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#539]
It is not clear from the code what the `Locking4Reputation` `totalLocked` and `totalLockedLeft` properties represent.  I'm not sure the code is correct by any interpretation.

After `_lock`, totalLocked is incremented and then totalLockedLeft = totalLocked .

After `_release`, totalLocked is unchanged while totalLockedLeft is decremented by the released amount.

Can we at least document and if needed, fix these properties?

**Comment by dkent600** [comment]
@orenyodfat

**Comment by orenyodfat** [comment]
This is done in order to add addition check and verify there is sum zero of the totalLocked .--> cannot redeem more than locked.

**Comment by dkent600** [comment]
Suppose:

1. lock 10
totalLockedLeft  = totalLocked  = 10
2. lock 10
totalLockedLeft  = totalLocked  = 20
3. release lockid 1
totalLockedLeft  = 10
totalLocked  = 20
4. lock 10
totalLockedLeft  = totalLocked  = 30

Does it make sense that total totalLockedLeft  is 30 after releasing in step 4?

**Comment by dkent600** [comment]
OK, it makes sense when one realises that one can only lock during the locking period and only redeem once the period has expired.
