### ISSUE TITLE
Auction4Reputation crashed on redeem when there were no bids

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#551]
This is just a heads up because I haven't had time to investigate.  I believe I have seen `Auction4Reputation.redeem` crash (not revert) when no bids have been made in the auction.

**Comment by orenyodfat** [comment]
please re check .
this line https://github.com/daostack/arc/blob/master/contracts/schemes/Auction4Reputation.sol#L90
suppose to guaranty it will not
