### ISSUE TITLE
Add metadata to a DAO

### ISSUE THREAD

**Issue by leviadam** [daostack/arc#589]
It seems very reasonable that a DAO would want to have metadata for the DAO. Things like manifesto, roadmap, description, maybe even color-palette in the future.
One can see this coming from the genesis alpha community, as something of the sort was suggested in a  [PR](https://github.com/daostack/alchemy/pull/215) in alchemy.

I suggest the avatar should have a metadata function, where all it is doing is emiting an event with the hash of an IPFS json file that will contain the metadata.

**Comment by orenyodfat** [comment]
so the intention is that a valid metadata will be consider the one get out of latest event ?

**Comment by leviadam** [comment]
Not necessarily. It can maybe have layers.
I think your way is the simplest though, so we should maybe adopt it for now.
But this is not really relevant for Arc in any case. Maybe it is for the caching though.
