### ISSUE TITLE
DAORegistry or DAORegistery?

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#614]
is spelled "DAORegistry" in migration/migration.json, and "DAORegistery" in the Arc .sol filename.

This breaks the migration verify script.

Arc is the one that is technically in error here.

**Comment by orenyodfat** [comment]
please move that to https://github.com/daostack/arc-hive

**Comment by dkent600** [comment]
https://github.com/daostack/migration/issues/109

**Comment by dkent600** [comment]
https://github.com/daostack/arc-hive/issues/6
