### ISSUE TITLE
Add a helper function to Redeemer.sol contract that executes a proposal and redeems the proposal's beneificiary rewards

### ISSUE THREAD

**Issue by tibetsprague** [daostack/arc#618]
After much discussion we on the Alchemy team feel that "executing" a ContributionReward should send the rewards to the beneficiary of the proposal. This will become more important as we have other proposals which on execution will immediately carry out their specific action. If the DAO doesn't have enough funds to pay for all the rewards thats ok those rewards will stick around on the Redemptions page. For now we are going to handle this using the Redeemer helper contract to execute and redeem the beneficiary's rewards at one time, the problem with this is that this also redeems other GenesisProtocol rewards for the current user, and we do want to separate that out into a separate call so that the current user can see what rewards they are receiving from the Genesis Protocol, and understand the protocol better

**Comment by tibetsprague** [comment]
@A-Zak does that sound right to you?

**Comment by orenyodfat** [comment]
He redeemer allow to specify which redeem you want (cr or gp ) .
If it not supported we might add that support .

**Comment by orenyodfat** [comment]
The

**Comment by dkent600** [comment]
@tibetsprague 

> If the DAO doesn't have enough funds to pay for all the rewards thats ok those rewards will stick around on the Redemptions page

The problem in that scenario is that it won't execute at all, not even at the GP level, is that correct?  What are the implications, then, for Alchemy?

@orenyodfat 

> He redeemer allow to specify which redeem you want (cr or gp ) .

I believe the ideal fix to Redeemer would just allow it to take a null _beneficiary.  When null it would not redeem the _beneficiary rewards.

I am guessing that `Redeemer.redeem` could work for any scheme, not just CR, when _beneficiary is null.  If we want to use it for all schemes, then we can't ever pass in _beneficiry != null, except for when the scheme is CR.  That is not very symmetrical, but I suppose an ugly but doable workaround.

Nor would it be very symmetrical to call `Redeemer.redeem` only ever for CR, and `GP.execute` for all other schemes; again I suppose an ugly but doable workaround.

**Comment by jellegerbrandy** [comment]
Consider though that separating "exeucting the proposal (= payout the beneificiery)" and "redeeming your citizen's rewards" is indeed clearer, but it does take away an incentive to click on that button.

**Comment by jellegerbrandy** [comment]
So, in a nutshell, a function in Redemeer.sol that will:

- call `executProposal` on the proposal (which updates the states)
- if it is a contributionReward, distribute the rewards as specificed

I.e., this is roughly what we thing that an average user would expect what "executing a proposal" mean. It is the current `redeem` function defined here: https://github.com/daostack/arc/blob/master/contracts/utils/Redeemer.sol#L47, minus the distribution of daobounty and citiizen's rewards (for voting and staking)

**Comment by orenyodfat** [comment]
Is that not what redeemed redeem function  is doing ? https://github.com/daostack/arc/blob/master/contracts/utils/Redeemer.sol#L19

**Comment by jellegerbrandy** [comment]
". It is the current redeem function defined here: https://github.com/daostack/arc/blob/master/contracts/utils/Redeemer.sol#L47, minus the distribution of daobounty and citiizen's rewards (for voting and staking)" :-)

**Comment by A-Zak** [comment]
Please see my comment in #513 
> One thing to note (which I hope is not an issue), is that the execution incentive seem to happen only when you call `executeBoosted`, which the current version of Redeemer doesn't do (Redeemer calls `execute`).
> 
> @leviadam, you mentioned earlier that using a helper contract is not a problem since execute doesn't care about `msg.sender`. well, it seems like `executeBoosted` does care.
> 
> I just wanted to make sure this is not a problem, and if so, that we find out now.
> 
> @jellegerbrandy @dkent600 @orenyodfat @tibetsprague

**Comment by orenyodfat** [comment]
Using an helper contract for the executeBoosted can be done as well by
different ways :
One way is to use a caller contract owned by the beneficiary which will do
the call . This caller contract can be created on the fly by the helper or
it can be passed to it as a param .

**Comment by A-Zak** [comment]
@orenyodfat what are the other ways? :D
I'm just curious... I trust your judgment and I'm ok with however you think is best ^_^

**Comment by orenyodfat** [comment]
This issue is still not clear to me . 
Please clarify , what is needed and why. 
It might be better to close this one and open a new clean one. @tibetsprague @A-Zak @jellegerbrandy

**Comment by jellegerbrandy** [comment]
closing this. See #624  for the original issue with which this confused discussion started. And I'll open a new issue to discuss a more generic `redeem` function that we can use for all types of proposals

**Comment by jellegerbrandy** [comment]
Nee issue #625 is meant to reset this discussion and start from scratch. Plz comment there, specifically oren and alex. :heart:
