### ISSUE TITLE
provide uint256 param to GenericScheme GenericCall

### ISSUE THREAD

**Issue by dkent600** [daostack/arc#620]
Feature request:  GenericScheme allows us to create proposals that result, upon execute, in calling a function on another contract.  The function is defined by the contract address and the ABI-encoded definition of the function.

A given instance of GenericScheme is configured, when deployed, with a single contract address on which to invoke functions.  From that contract, each GenericScheme proposal may specify a function (ABI) that will be invoked upon GenericScheme.execute.  Each proposal may also specify an ETH amount to transfer to the contract when the funciton is invoked.

However, when creating proposals, it is not possible to specify parameters that may be passed to the contract function.  Just a single uint256 parameter could provide the contract with context that informs the contract function about what to do when it is invoked.

Without such contextual information, a given contract function knows not *why* it is being invoked, beyond the single dimension of having been invoked.

A use-case I have in mind is a contract function to which we may pass a proposalId that is provided to the GenericScheme proposal upon creation of the GenericScheme proposal.  This proposalId param would identify proposals on other schemes in the DAO, for example, ContributionReward.  Perhaps the invoked contract would use that proposalId to implement multi-target rewards, reward escrows, or deal with proposals that have been voted to be malicious.

Or course, the uint256 param needn't identify a proposalId, but could be an address or anything else that would fit within that size.

**Comment by dkent600** [comment]
The param would be automatically supportable by dApp GUIs such as Alchemy, without requiring any custom code.

**Comment by orenyodfat** [comment]
if the `invoked contract ` would like to get some additional param it should define that on its function  params. what we are missing here ?

**Comment by dkent600** [comment]
> if the invoked contract would like to get some additional param it should define that on its function params. what we are missing here ?

The idea is that GenericScheme would pass the _value_ of the addition `uint256` param to the `invoked contract function`.

**Comment by orenyodfat** [comment]
For what ? If the invoked contract needs some additional param it should
define it in its function abi params

**Comment by dkent600** [comment]
> If the invoked contract needs some additional param it should
define it in its function abi params

How do you propose that the contract receive the param _value_?  I am not aware that an ABI can specify parameter _values_.  Am I wrong?

**Comment by orenyodfat** [comment]
genericScheme (and eventually genericCall) can invoke any function with any
number and types of parameters .

**Comment by dkent600** [comment]
1) I am trying to design a GenesisScheme that can be registered with the DAO and used in Alchemy without having to write any custom code in Alchemy.

2) I am trying to avoid the user having to construct and submit an ABI

Asking the user to supply an ABI is very unfriendly.  Asking the dApp, such as Alchemy, to hardcode arbitrary ABIs requires writing custom code for every GenericScheme.

I am asking to support just one additional parameter.  I know it doesn't cover all cases, but it covers a lot of cases (I described three above).  It is a lot better than the alternatives.

**Comment by A-Zak** [comment]
It sounds to me like the beginning of generic scheme templates, with this being the first template - single Parma function...

@dkent600 - is that close enough, or am I missing anything? :)

**Comment by dkent600** [comment]
@A-Zak 

The idea I proposed in this ticket is not viable.  I didn't realize that one can supply param values in an ABI.

I woke up this morning with an idea for how to do this. Will close this ticket and create another on that.
