### ISSUE TITLE
Calling Redeemer.redeem on unexecuted proposal doesnt work as expected

### ISSUE THREAD

**Issue by tibetsprague** [daostack/arc#624]
What should happen is that the proposal is executed and then the GP and CR rewards are redeemed, what does happen is that the proposal is executed and GP rewards are redeemed but the CR ones are not.

**Comment by orenyodfat** [comment]
Does [this](https://github.com/daostack/arc/blob/master/test/contributionreward.js#L471) test does not verify the claim in this issue ?

**Comment by jellegerbrandy** [comment]
@tibetsprague we need some more detail on how to reproduce this; this Or even better: a transaction on etherscan.

**Comment by tibetsprague** [comment]
@orenyodfat that test doesn't test the case I'm talking about which is calling Redeemer.redeem on an un-executed proposal, specifically an expired, boosted proposal that has not yet been executed.

**Comment by orenyodfat** [comment]
well, how about [this one](https://github.com/daostack/arc/blob/cr-test/test/contributionreward.js#L519)  .
calling Redeemer.redeem on an un-executed proposal, specifically an expired, boosted proposal that has not yet been executed. 
and there is cr rewards.

**Comment by A-Zak** [comment]
btw, @tibetsprague we know what went wrong here....
We accidentally copied some example params and set the proposal creation params to split the reward in 5, and give a 12 seconds delay. so would actually need to wait 12 seconds after executing the proposal, and calling redeemer redeem attempted to do it imediately... should be patched now...

**Comment by A-Zak** [comment]
@orenyodfat I think you can close this issue.
