### ISSUE TITLE
We need a generic `redeem()` function that works for all proposal schemes

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/arc#625]
As the title says.  The current `redeem()` function on`Redeemer.sol` is written specifically for contributionReward.  

This may be a good opportunity to refactor this helper functions (which has led to a lot of confusion, because it's semantics is not so very clear). 

What we probably like to have is a 

* A generic function on Redeemer.sol called `redeemGPRewards()` which the `redeem` and `redeemDAoBounty` functions of the genesisprotocol in a single transcation (i.e. lines https://github.com/daostack/arc/blob/master/contracts/utils/Redeemer.sol#L67 to line 71)

* A function `executeProposal(proposalId, proposalType)` that will **do what is proposed in the proposal**: in the case of contribution rewards, call this function https://github.com/daostack/arc/blob/master/contracts/utils/Redeemer.sol#L80; in the case of GenericSchemes, execute the function call, etc. (This can also be a series of functions such as `executeContributionReward`, `executeGenericScheme`, etc)

* A function that combines the two actions in a single transction, `redeemGPRewardsAndExecuteProposal`, which does  exactly what https://github.com/daostack/arc/blob/master/contracts/utils/Redeemer.sol#L47 was intended to do in the case of CR, but will work also for other schemes

I  think this is a good pattern to follow on Redeemer.sol, and gives us the flexibility to choose appropriate UX actios for our "execute" and "redeem" buttons.

**Comment by orenyodfat** [comment]
`A generic function on Redeemer.sol called redeemGPRewards() which the redeem and redeemDAoBounty functions of the genesisprotocol in a single transcation (i.e. lines https://github.com/daostack/arc/blob/master/contracts/utils/Redeemer.sol#L67 to line 71)`

This can be achieved using the current redeemer redeem() function. which execute (if needed) and get the gp rewards.

`A function executeProposal(proposalId, proposalType) that will do what is proposed in the proposal: in the case of contribution rewards, call this function https://github.com/daostack/arc/blob/master/contracts/utils/Redeemer.sol#L80; in the case of GenericSchemes, execute the function call, etc. (This can also be a series of functions such as executeContributionReward, executeGenericScheme, etc)`

For the case of GenericScheme   - executeProposal can be called only by the voting machine, if that revert in the calling contract for any reason ... the user can call execute to try again.
For this case alchemy does not need an helper (which will require more gas) it can call GeneticScheme `execute` directly.

`A function that combines the two actions in a single transction, redeemGPRewardsAndExecuteProposal, which does exactly what https://github.com/daostack/arc/blob/master/contracts/utils/Redeemer.sol#L47 was intended to do in the case of CR, but will work also for other schemes`

Which other schemes ? the only  one which I see now is GenericScheme and this only for a unique (rare) case that the called contract reverts on the original call which is trigger by the voting machine.
in this case it will be cheaper to call 'execute' directly to the GenericScheme.

**Comment by orenyodfat** [comment]
This [test](https://github.com/daostack/arc/blob/redeemer_test/test/contributionreward.js#L519) confirm that calling redeemer redeem with beneficiary NULL redeemed only ContributionRewards rewards.
