### ISSUE TITLE
Question: Why is msg.sender added as a scheme to new organizations?

### ISSUE THREAD

**Issue by dOrgJelli** [daostack/arc#639]
What is the use-case for this functionality?

Controller Instances: https://github.com/daostack/arc/blob/f5e16c2b78d85e7290b32b145524667e80c405e3/contracts/controller/Controller.sol#L73

New UController Organizations: https://github.com/daostack/arc/blob/f5e16c2b78d85e7290b32b145524667e80c405e3/contracts/controller/UController.sol#L104

**Comment by ben-kaufman** [comment]
This is because when deploying a DAO you must have a way to first initialize it with all the needed schemes. By having the creator of the DAO as a scheme with all the permissions at first you can register all needed schemes with that account and then revoke it's permissions when all is initialized.

**Comment by dOrgJelli** [comment]
ahh okay that makes sense, thank you! :)

**Comment by orenyodfat** [comment]
To allow the one which creating the org to register all other schemes .
