### ISSUE TITLE
Unable to redeem USDC

### ISSUE THREAD

**Issue by orishim** [daostack/arc#642]
We sent 1 USDC to dOrg DAO and tried to withdraw through a proposal. The redemption transaction succeeds but the token does not leave the DAO.

See these two test proposals:

Proposal:
https://alchemy.daostack.io/dao/0xbe1a98d3452f6da6e0984589e545d4fc25af7526/proposal/0x518f141328e36c4d24f2a1f03eebea502ca5ff7900fd735732d4dd3e2d5d095e
Redeem tx:
https://etherscan.io/tx/0xe67f0ce8bd2191bc455471d58ee65c40f70ede3232387213d0b83790b19e8fdc

Proposal: https://alchemy.daostack.io/dao/0xbe1a98d3452f6da6e0984589e545d4fc25af7526/proposal/0x1203ccea03fed16aad5a6c412d47d6e08be2dcaa0fe2532606ca6cb08881b525
Redeem tx:
https://etherscan.io/tx/0x9a0965bca2d8dc9016c07c8432f50f248f9f07005dc35fbae3bf54e00ca46e35

**Comment by orenyodfat** [comment]
well, USDC has 6 decimals .https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48#readContract

the proposal is reward with 1000000000000000000 which is far more than the dao hold.
it might be a bug in alchemy though ...

**Comment by orenyodfat** [comment]
see https://github.com/daostack/alchemy/issues/795
