### ISSUE TITLE
Redeemer.redeem fails in proposals that are expiredinQueue

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/arc#643]
If the propsal state is `expiredInQueue`, the redeemer contracts `redeem()`  [will call genesisProtocol.redeemDaoBounty](https://github.com/daostack/arc/blob/master/contracts/utils/Redeemer.sol#L70).

However, `genesisProtocol.redeemDaoBounty` requires that the proposal be in the `Executed` state: https://github.com/daostack/infra/blob/master/contracts/votingMachines/GenesisProtocolLogic.sol#L401

And so the transaction will fail.

**Comment by jellegerbrandy** [comment]
We can do a workaround by calling `redeem` on the GP protocol directly for expiredInQueue proposals.

**Comment by orenyodfat** [comment]
Thanks .
It should be fixed
