### ISSUE TITLE
Bug in the redeem function of the GenesisProtocolLogic.sol 

### ISSUE THREAD

**Issue by arsena21** [daostack/arc#654]
I've been working with Jordan to figure out why my DAO can't redeem via GenesisProtocol scheme. 

These DAOs are specifically DAOfund Manager (which passed a proposal to give DAOfund rep - but can't be redeemed that propsal: https://alchemy.daostack.io/dao/0xf7a9f5ef74a94f19f75356aa959cb0afaf421bab/proposal/0xb38879826c8f3f54d345ccdee01e42890bb9d61ab4f8112da18e25009482048a), and DAOfund (which passed a proposal to redeem via GenesisProtocol, but can't redeem: https://alchemy.daostack.io/dao/0xe8e1d0f1783b22ff409deb14fa5acc9cce2a3d15/proposal/0x4bff8d5be1d9b7d5cabed2e5f4235a9ebdec3a6ebed637a702111452afba8303).

"An off the cuff guess after a bit of digging: I think there might be a bug in the redeem function of the GenesisProtocolLogic.sol contract. It deals with DAO redemptions and voter redemptions seperately, and I think there's a bug in the logic here."
-Jordan

**Comment by jellegerbrandy** [comment]
_what_ would be the bug?

**Comment by dOrgJelli** [comment]
Hey sorry for the vagueness here @jellegerbrandy, I dug into the issue for ~30 minutes then had to run, and I left off thinking that this code needed more analysis to see if it was the cause of the issue: https://github.com/daostack/infra/blob/9b45fc0eb86ee3043f1eb838cb8504cdb7b5947e/contracts/votingMachines/GenesisProtocolLogic.sol#L335-L370

I would definitely not recommend starting the digging here though, this is purely a hunch and I'm not that knowledgeable of this contract's specifics. Just something to have in mind when digging :)

**Comment by orenyodfat** [comment]
Thanks Jordan ,
If there indeed a bug , please provide a test/code to verify that.

**Comment by dOrgJelli** [comment]
Definitely agree @orenyodfat, sorry about the confusion. I think a better title for the issue would be "Cannot Redeem Using DAO to DAO Generic Action".

**Comment by orenyodfat** [comment]
Is that related to this repo? Or alchemy repo?

**Comment by orenyodfat** [comment]
Please note that GenesisProtocol cares only re the msg.sender (it does not
care if it is a dao or “regular” user).
So if a dao act(vote/propose/stake) via its avatar(msg.sender) it should be
able to redeem to its avatar.
It is a matter of the right call passed via the generic action(redeem ) .

**Comment by dOrgJelli** [comment]
I agree, starting at the Alchemy repo would be a better first step, my bad. @arsena21 would you want to repost here: https://github.com/daostack/alchemy

**Comment by dkent600** [comment]
Would be nice if the `GenesisProtocolLogic.redeem` function did a `require` on the input arguments, that they are non-null.

**Comment by dkent600** [comment]
To be clear, `GenesisProtocol.redeem` does not use `mgs.sender`.  The beneficiary is a parameter:

```
redeem(bytes32 _proposalId, address _beneficiary)
```
