### ISSUE TITLE
Redeemer.redeem only works with contributionReward proposals

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/arc#655]
we now, as a workaround, to redeem a non-CR proposal, get some CR contract that is deployed (it does not matter which), and use that address as the first argument to the redeem function

It works but is not so good :-)

**Comment by dkent600** [comment]
In the meantime, can we give folks some work-around instructions using etherscan.io?

**Comment by jellegerbrandy** [comment]
It is still usable also like this, just clumsy

**Comment by dkent600** [comment]
Yeah, I just wanted something to work-around until this work-around is published, which could be several days.

**Comment by jellegerbrandy** [comment]
closing this as we have no problems :-)
