### ISSUE TITLE
Locking twice in ContinuousLockingToken4Reputation 

### ISSUE THREAD

**Issue by leviadam** [daostack/arc#663]
https://github.com/daostack/arc/blob/2b8d465931294d2fdadfbe7f9045c53bd2cce651/contracts/schemes/ContinuousLockingToken4Reputation.sol#L29

@orenyodfat, should this mapping not be 
`mapping(address => mapping(bytes32=>uint)) scores;`
In order not to run over it when user is locking twice.

@tspoff got my attention to that.

**Comment by orenyodfat** [comment]
good catch @tspoff

**Comment by orenyodfat** [comment]
though mapping(bytes32=>uint) scores; will do the work I guess

**Comment by leviadam** [comment]
I think so, but we have to be sure there is no edge case.
