### ISSUE TITLE
Controller's Creator == Rogue Scheme

### ISSUE THREAD

**Issue by dOrgJelli** [daostack/arc#680]
Currently (if I'm not mistaken), there's no way for the Subgraph to know if the creator of the Controller (msg.sender) is currently added as a full permission scheme or not. This is a huge security vulnerability.

https://github.com/daostack/arc/blob/03c4350b022d740bf90f65a355d9fbea8d289480/contracts/controller/Controller.sol#L73

**Comment by orenyodfat** [comment]
Yes . A registerScheme event might be helpful here as the subgraph and
alchemy can then display this “admin” scheme.
Though this is not enough .
There still a need for audit the dao deployment .
This thing Is currently checked manually as part of a dao deployment audit
process .
One way to verify that this “admin” scheme is unregister is to verify that
there is an unregisterscheme event without a corresponding register scheme
event .

**Comment by orenyodfat** [comment]
@dOrgJelli by running a script for detecting that I found 1 potential `problematics` dao :

```
BetterBrooklyn is using UController
avatar 0x74504b811bbf357edb6daa8346d51f6dd113113f
controller 0x9868f32D9A2C3533b56D718deec68cDDc2E55A51
admin scheme with full permission which is not a contract:  0x151C2E684Af34137E7276dd79C0fE4120a49F02f 
```

- we need to check if this was the intention of the dao deployer . I am not sure :)

**Comment by dOrgJelli** [comment]
> One way to verify that this “admin” scheme is unregister is to verify that
there is an unregisterscheme event without a corresponding register scheme
event .

Agreed, this would be a good way to detect it, but you still wouldn't be able to know what the address of the admin scheme was unless you were able to check who deployed the contract.
