### ISSUE TITLE
Should ContributionRewardExt.proposeContributionReward Be `onlyRewarder` Restricted?

### ISSUE THREAD

**Issue by dOrgJelli** [daostack/arc#739]
Should the signature of [this function](https://github.com/daostack/arc/blob/50ae0685769750a2e1d77a973fe49351bae5238c/contracts/schemes/ContributionRewardExt.sol#L154) have the `onlyRewarder` modifier? I can't think of a case where it's desired to have it called directly and not by the rewarder, this feels like a vulnerability.

**Comment by orenyodfat** [comment]
no.
this scheme can be used also as "normal" ContributionReward (without a rewarder).
